# Generated by Django 5.0 on 2023-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_modules', '0002_customuser_about_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_uploader',
            field=models.BooleanField(default=False),
        ),
    ]
