# Generated by Django 5.0 on 2023-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
