# Generated by Django 5.0 on 2023-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_budget_movies_cast_movies_country_movies_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='production_companies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
