# Generated by Django 5.0 on 2023-12-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_production_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='crew',
        ),
    ]
