# Generated by Django 5.0 on 2023-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movies_crew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='cast',
            new_name='cast_and_crew',
        ),
    ]
