# Generated by Django 5.0 on 2023-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_cast_movies_cast_and_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='content_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='revenue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='runtime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
