# Generated by Django 5.0 on 2023-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movies_budget_alter_movies_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_companies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
