# Generated by Django 5.0 on 2023-12-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movies_genre_alter_movies_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobject',
            name='season',
            field=models.IntegerField(default=0),
        ),
    ]
