# Generated by Django 5.0 on 2023-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_trackobject_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobject',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackobject',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
