# Generated by Django 5.0 on 2023-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_trackobject_synopsis_trackobject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobject',
            name='show',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
