# Generated by Django 5.0 on 2023-12-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_castobjects_content_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast_and_crew',
        ),
    ]
