# Generated by Django 5.0 on 2023-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_movies_cast_and_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='episodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
