# Generated by Django 5.0 on 2023-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
