# Generated by Django 5.0 on 2023-12-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notifications.notification'),
        ),
    ]
