# Generated by Django 5.0 on 2023-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_likes_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
